source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '11.0'

target 'KTUILibrary_Example' do
  pod 'KTUILibrary', :path => '../'
  pod 'SDWebImage'
	pod 'KTFoundation', '~> 1.0.6'

end
