source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'KTUILibrary_Example' do
  pod 'KTUILibrary', :path => '../'
  pod 'SDWebImage'
	
	post_install do |installer|
		installer.pods_project.build_configurations.each do |config|
			config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
		end
	end
end
